{
  description = "Unsloth Studio: AGPL-licensed CLI + web UI assembled from the unslothai/unsloth source tree.";

  inputs = {
    # Heavy AI deps (torch, vllm, bitsandbytes, flash-attn, xformers, …) live on unstable.
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    flake-lib = {
      url = "github:jgus/flake-lib/v1";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.follows = "flake-utils";
    };
    # The Apache unsloth / unsloth-zoo libs come from nixpkgs but lag upstream; these sibling flakes overlay a version bump. Composed into overlays.default below so a single consumer overlay carries all three. Tracking main = latest released version.
    unsloth = {
      url = "github:jgus/unsloth-flake";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.follows = "flake-utils";
      inputs.flake-lib.follows = "flake-lib";
    };
    unsloth-zoo = {
      url = "github:jgus/unsloth-zoo-flake";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.follows = "flake-utils";
      inputs.flake-lib.follows = "flake-lib";
    };
  };

  outputs = { self, nixpkgs, flake-utils, flake-lib, unsloth, unsloth-zoo }:
    let
      # Single source of truth for the upstream rev + the hashes that depend on it. Regenerate via `nix run .#update-version` from this directory.
      pin = import ./pin.nix;
      inherit (pin) version sourceRev sourceHash npmDepsHash;
      source = { type = "github"; owner = "unslothai"; repo = "unsloth"; };

      # Overlay is the package definition; the per-system `packages` output below just extracts it.
      overlay = final: prev:
        let
          src = final.fetchFromGitHub {
            owner = "unslothai";
            repo = "unsloth";
            rev = sourceRev;
            hash = sourceHash;
          };
          unsloth-studio-frontend = final.callPackage ./pkgs/unsloth-studio-frontend { inherit src version npmDepsHash; };
        in
        {
          inherit unsloth-studio-frontend;
          # Inject into the python3 scope so `python3.withPackages (ps: [ ps.unsloth-studio ])` works.
          python3 = prev.python3.override (old: {
            packageOverrides = nixpkgs.lib.composeExtensions
              (old.packageOverrides or (_: _: { }))
              (pyfinal: _pyprev: {
                unsloth-studio = pyfinal.callPackage ./pkgs/unsloth-studio {
                  inherit src version unsloth-studio-frontend;
                };
              });
          });
        };

      # Single consumer-facing overlay: the unsloth / unsloth-zoo version bumps plus the studio injection. Order is zoo, then unsloth, then studio — each overrides nixpkgs' python3 scope independently, so the bumped libs are present when studio's dependencies resolve.
      composedOverlay = nixpkgs.lib.composeManyExtensions [
        unsloth-zoo.overlays.default
        unsloth.overlays.default
        overlay
      ];
    in
    flake-utils.lib.eachDefaultSystem
      (system:
        let
          pkgs = import nixpkgs {
            inherit system;
            config.allowUnfree = true;
            overlays = [ composedOverlay ];
          };
        in
        {
          packages = {
            inherit (pkgs) unsloth-studio-frontend;
            inherit (pkgs.python3.pkgs) unsloth-studio;
            # Vendored frontend lockfile + npmDepsHash and upstream-deps.nix are regenerated by the artifactHook.
            update-version = flake-lib.lib.mkUpdateVersion {
              inherit pkgs source;
              buildAttr = "unsloth-studio";
              extraHashes = [ "npmDepsHash" ];
              artifactHook = ./regen-artifacts.sh;
            };
            update-branches = flake-lib.lib.mkUpdateBranches {
              inherit pkgs source;
              pinSchema = "github-npm";
              branchOwnedFiles = [ "pin.nix" "flake.lock" "pkgs/unsloth-studio-frontend" "pkgs/unsloth-studio/upstream-deps.nix" ];
              # Upstream tags 0.1.405-beta as a hotfix on 0.1.40 (released between 0.1.39 and 0.1.41), but 405 sorts above 44. Remap so it sorts as 0.1.40.5.
              versionOverrides = { "0.1.405-beta" = "0.1.40.5-beta"; };
            };
            default = pkgs.python3.pkgs.unsloth-studio;
          };
        }) // {
      overlays.default = composedOverlay;
    };
}
