#!/usr/bin/env -S nix shell nixpkgs#python3 --command python3
# Derives pkgs/unsloth-studio/upstream-deps.nix from the upstream source tree's declared runtime requirements. Invoked by update-version.sh after the new rev is fetched. Reads:
#   pyproject.toml                                  - [project].dependencies + [project.optional-dependencies].huggingfacenotorch
#   studio/backend/requirements/studio.txt          - studio backend runtime deps
#   studio/backend/requirements/base.txt            - unsloth + unsloth-zoo
# Names are normalized per PEP 503 (lowercase, [-_.] runs collapsed to '-'). The output is a plain Nix list; default.nix layers in `extraDeps` (deps upstream doesn't declare but Studio needs at runtime) and `excludeDeps` (deps upstream declares but we intentionally don't ship, e.g. CUDA-only bits or build-time-only entries).

import re
import sys
import tomllib
from pathlib import Path


def normalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def parse_requirement(line: str) -> str | None:
    line = line.split("#", 1)[0].strip()
    if not line:
        return None
    m = re.match(r"^([A-Za-z0-9][A-Za-z0-9_.\-]*)", line)
    return normalize(m.group(1)) if m else None


def parse_txt(path: Path) -> set[str]:
    return {n for line in path.read_text().splitlines() if (n := parse_requirement(line))}


def parse_pyproject(path: Path) -> set[str]:
    data = tomllib.loads(path.read_text())
    out: set[str] = set()
    project = data.get("project", {})
    for req in project.get("dependencies", []) or []:
        if n := parse_requirement(req):
            out.add(n)
    extras = project.get("optional-dependencies", {}) or {}
    # huggingfacenotorch is upstream's no-cuda runtime dep set — the closest match to what Studio actually needs at runtime. The huggingface / windows / cuXXX extras layer on cuda-bound wheels we deliberately skip.
    for req in extras.get("huggingfacenotorch", []) or []:
        if n := parse_requirement(req):
            out.add(n)
    return out


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <upstream-src-dir> <output-nix-file>", file=sys.stderr)
        return 2
    src = Path(sys.argv[1])
    out = Path(sys.argv[2])

    deps: set[str] = set()
    deps |= parse_pyproject(src / "pyproject.toml")
    deps |= parse_txt(src / "studio" / "backend" / "requirements" / "studio.txt")
    deps |= parse_txt(src / "studio" / "backend" / "requirements" / "base.txt")

    if not deps:
        print("error: parsed zero runtime deps from upstream — source layout changed?", file=sys.stderr)
        return 1

    body = "\n".join(f'  "{n}"' for n in sorted(deps))
    out.write_text(
        "# Auto-generated by `nix run .#update-version`. Do not edit by hand.\n"
        "# Derived from upstream pyproject.toml + studio/backend/requirements/{studio,base}.txt\n"
        "# at the rev pinned in pin.nix. Names normalized per PEP 503.\n"
        "# default.nix layers `extraDeps` and `excludeDeps` on top of this list.\n"
        f"[\n{body}\n]\n"
    )
    print(f"  wrote {len(deps)} deps to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
