{ lib
, buildPythonPackage
, setuptools
, src
, version
, unsloth-studio-frontend
, writeText
, python  # back-reference to the interpreter; `python.pkgs` is the python3Packages scope this derivation is built against
}:
# Combined unsloth_cli + studio Python package, AGPL. The two are tightly coupled (CLI imports studio.backend) so we ship them together. The Apache-licensed `unsloth/` python lib is supplied by nixpkgs and stripped from our source tree to avoid duplication.
let
  # Replaces upstream's pyproject.toml so we drop:
  #   - the dynamic version attr that read unsloth.models._utils.__version__ (we rm the unsloth/ subtree below)
  #   - everything except the unsloth_cli + studio packages
  #   - obsolete runtime dep version pins
  pyprojectFile = writeText "pyproject.toml" ''
    [build-system]
    requires = ["setuptools"]
    build-backend = "setuptools.build_meta"

    [project]
    name = "unsloth-studio"
    version = "${version}"
    description = "Unsloth Studio: web UI for training and running open models"
    readme = "README.md"
    license = "AGPL-3.0-only"
    requires-python = ">=3.9,<3.15"
    dependencies = ["typer", "pydantic", "pyyaml", "nest-asyncio"]

    [project.scripts]
    unsloth = "unsloth_cli:app"

    [tool.setuptools]
    include-package-data = true

    [tool.setuptools.packages.find]
    include = ["unsloth_cli*", "studio", "studio.backend*"]
    exclude = ["tests*"]

    [tool.setuptools.package-data]
    studio = [
      "*.sh",
      "*.ps1",
      "*.bat",
      "frontend/dist/**/*",
      "frontend/*.json",
      "frontend/*.html",
      "backend/requirements/**/*",
      "backend/plugins/**/*",
      "backend/core/data_recipe/oxc-validator/*.json",
      "backend/core/data_recipe/oxc-validator/*.mjs",
    ]
  '';
in
buildPythonPackage {
  pname = "unsloth-studio";
  inherit version;
  pyproject = true;

  inherit src;

  postPatch = ''
    # Strip out upstream pieces we don't ship from this derivation:
    #   unsloth/        — nixpkgs Apache lib supplies it
    #   tests/          — not relevant to a runtime image
    #   images/         — repo-level docs assets
    #   scripts/        — local-dev helpers
    #   src-tauri/      — desktop wrapper (we run headless)
    #   build.sh / cli.py / unsloth-cli.py — entry shims, replaced by setuptools
    rm -rf \
      unsloth \
      tests \
      images \
      scripts \
      src-tauri \
      build.sh \
      cli.py \
      unsloth-cli.py

    # Overlay the nix-built frontend assets onto studio/frontend/dist.
    rm -rf studio/frontend/dist
    cp -r ${unsloth-studio-frontend} studio/frontend/dist
    chmod -R u+w studio/frontend/dist

    cp ${pyprojectFile} pyproject.toml
  '';

  build-system = [ setuptools ];

  # Runtime deps are derived in two layers:
  #   1. `upstreamDeps`: auto-generated from upstream pyproject.toml + studio/backend/requirements/{studio,base}.txt at the pinned rev. Regenerated by `nix run .#update-version`. Sorted, PEP 503-normalized PyPI names.
  #   2. `extraDeps` / `excludeDeps` below: hand-curated knobs to fill in deps Studio needs but upstream doesn't declare, and to drop entries upstream declares but we don't ship (heavy CUDA bits / build-only tools).
  # Names map directly to attrs in `python.pkgs`. If a build hard-fails with "attribute X missing", the upstream dep isn't in nixpkgs — add it to `excludeDeps` (and to `extraDeps` under the correct nixpkgs attr if a substitute exists).
  dependencies =
    let
      upstreamDeps = import ./upstream-deps.nix;

      # Deps upstream doesn't list as runtime requirements but Studio's backend imports at startup:
      #   - web stack: fastapi pulls starlette transitively but we want explicit pins for sse-starlette, websockets, python-multipart used by the studio routes; aiohttp is used by a couple of provider clients
      #   - torch family: huggingfacenotorch deliberately omits torch so the CPU-only path can install; we run with cuda so they're hard requirements
      #   - safetensors / tokenizers: transitive via transformers in pip-land, but listing explicitly under nix avoids surprises if a future nixpkgs override drops them
      #   - misc backend modules referenced at import time
      extraDeps = [
        "aiohttp"
        "python-multipart"
        "sse-starlette"
        "starlette"
        "websockets"

        "hf-xet"
        "safetensors"
        "tokenizers"

        "gguf"
        "tiktoken"

        "torch"
        "torchaudio"
        "torchvision"
        "triton"

        "pillow"
        "scikit-learn"
        "scipy"

        "gitpython"
        "jinja2"
        "msgspec"
        "requests"
        "tabulate"
      ];

      # Deps upstream declares that we deliberately skip:
      #   - wheel: build-tool, not a runtime dep
      # Heavy CUDA-only bits (bitsandbytes / flash-attn / vllm / xformers) would also belong here if upstream's huggingfacenotorch ever names them; Studio's chat path lazy-imports them and those wheels ride open-PR cuda-build risks.
      excludeDeps = [
        "wheel"
      ];

      selectedNames = lib.subtractLists excludeDeps (lib.unique (upstreamDeps ++ extraDeps));
    in
    map (n: python.pkgs.${n}) selectedNames;

  # The CLI module is a typer app that imports studio.backend at invoke time; importing it eagerly here pulls in ~200MB of torch/transformers init paths for no real verification value.
  pythonImportsCheck = [ "unsloth_cli" "studio" ];

  meta = {
    description = "Unsloth Studio: web UI + CLI for training and running open models locally";
    homepage = "https://github.com/unslothai/unsloth";
    license = lib.licenses.agpl3Only;
    mainProgram = "unsloth";
    platforms = lib.platforms.linux;
  };
}
