[
  { name = "accelerate"; requirement = "accelerate>=0.34.1"; marker = null; }
  { name = "boto3"; requirement = "boto3>=1.34.0"; marker = null; }
  { name = "cryptography"; requirement = "cryptography>=42.0.0"; marker = null; }
  { name = "datasets"; requirement = "datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1"; marker = null; }
  { name = "datasets"; requirement = "datasets==4.3.0"; marker = null; }
  { name = "ddgs"; requirement = "ddgs"; marker = null; }
  { name = "diceware"; requirement = "diceware"; marker = null; }
  { name = "diffusers"; requirement = "diffusers"; marker = null; }
  { name = "fastapi"; requirement = "fastapi"; marker = null; }
  { name = "fastmcp"; requirement = "fastmcp>=3.0.2"; marker = null; }
  { name = "hf-transfer"; requirement = "hf_transfer"; marker = null; }
  { name = "httpx"; requirement = "httpx>=0.27.0"; marker = null; }
  { name = "huggingface-hub"; requirement = "huggingface-hub==0.36.2"; marker = null; }
  { name = "huggingface-hub"; requirement = "huggingface_hub>=0.34.0"; marker = null; }
  { name = "matplotlib"; requirement = "matplotlib==3.10.9"; marker = null; }
  { name = "nest-asyncio"; requirement = "nest-asyncio"; marker = null; }
  { name = "nest-asyncio"; requirement = "nest_asyncio"; marker = null; }
  { name = "numpy"; requirement = "numpy"; marker = null; }
  { name = "packaging"; requirement = "packaging"; marker = null; }
  { name = "pandas"; requirement = "pandas"; marker = null; }
  { name = "peft"; requirement = "peft!=0.11.0,>=0.18.0"; marker = null; }
  { name = "protobuf"; requirement = "protobuf"; marker = null; }
  { name = "psutil"; requirement = "psutil"; marker = null; }
  { name = "pydantic"; requirement = "pydantic"; marker = null; }
  { name = "pyjwt"; requirement = "pyjwt"; marker = null; }
  { name = "pymupdf"; requirement = "pymupdf==1.27.2.3"; marker = null; }
  { name = "pymupdf4llm"; requirement = "pymupdf4llm==0.3.4"; marker = null; }
  { name = "python-docx"; requirement = "python-docx==1.2.0"; marker = null; }
  { name = "pyyaml"; requirement = "pyyaml"; marker = null; }
  { name = "rich"; requirement = "rich"; marker = null; }
  { name = "sentence-transformers"; requirement = "sentence-transformers"; marker = null; }
  { name = "sentencepiece"; requirement = "sentencepiece>=0.2.0"; marker = null; }
  { name = "sqlite-vec"; requirement = "sqlite-vec==0.1.9"; marker = null; }
  { name = "structlog"; requirement = "structlog>=24.1.0"; marker = null; }
  { name = "tqdm"; requirement = "tqdm"; marker = null; }
  { name = "transformers"; requirement = "transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3"; marker = null; }
  { name = "trl"; requirement = "trl!=0.19.0,<=0.24.0,>=0.18.2"; marker = null; }
  { name = "typer"; requirement = "typer"; marker = null; }
  { name = "typer"; requirement = "typer>=0.12.0"; marker = null; }
  { name = "tyro"; requirement = "tyro"; marker = null; }
  { name = "unsloth"; requirement = "unsloth"; marker = null; }
  { name = "unsloth-zoo"; requirement = "unsloth-zoo"; marker = null; }
  { name = "unsloth-zoo"; requirement = "unsloth_zoo>=2026.7.6"; marker = null; }
  { name = "uvicorn"; requirement = "uvicorn"; marker = null; }
  { name = "wheel"; requirement = "wheel>=0.42.0"; marker = null; }
]
